[tool.poetry]
name = "cachew"
version = "0.1.0"
description = ""

authors = ["Dima Gerasimov <karlicoss@gmail.com>"]

# license = "MIT"

# readme = 'README.md'  # Markdown files are supported

# repository = "https://github.com/python-poetry/poetry"
# homepage = "https://github.com/python-poetry/poetry"

# keywords = ['packaging', 'poetry']

[tool.poetry.dependencies]
python = ">=3.6"

[tool.poetry.dev-dependencies]
pytest = "^5.3.2"
pylint = "^2.4.4"
mypy = "^0.750"
pytz = { version = "^2019.3", optional = true }

[tool.poetry.extras]
testing = ['pytest', 'pytz'] # , 'pylint', 'mypy', 'bandit']

[tool.pylint]

# poetry install
# poetry install -E testing
# poetry run pytest


# [2019-12-15 Sun 09:27] ok, so far seems that quite a few tools don't support pyproject.toml
# TODO do that for dataclasses https://python-poetry.org/docs/versions/#python-restricted-dependencies

# needed for tox? https://python-poetry.org/docs/faq/#is-tox-supported
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"