version: 2

jobs:
  build_and_check:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout

      # TODO preserve apt and pip caches?
      - run: sudo apt install python3-pip tox
      - run: python3 -m pip install --user tox

        # TODO use different versions of python
      - run: tox

workflows:
  version: 2

  build_and_check:
    jobs:
      - build_and_check
